spring:
  application:
    name: university-management-service
  datasource:
    url: jdbc:mysql://localhost:3306/university_flutter?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8055
